"""ORM models. The schema itself is owned by hand-written Alembic migrations (RLS policies and
exclusion constraints can't be autogenerated), so these classes must mirror migrations/versions/*.
"""

import enum
import uuid
from datetime import datetime, time
from typing import Any

from sqlalchemy import BigInteger, DateTime, Enum, ForeignKey, SmallInteger, Text, Time, func
from sqlalchemy.dialects.postgresql import CITEXT, JSONB, TSTZRANGE, UUID, Range
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    type_annotation_map = {dict[str, Any]: JSONB, uuid.UUID: UUID(as_uuid=True)}


def pg_enum(enum_cls: type[enum.Enum], name: str) -> Enum:
    """Map a Python enum to an existing Postgres enum type, storing .value (not the member name)."""
    return Enum(
        enum_cls,
        name=name,
        create_type=False,
        values_callable=lambda members: [m.value for m in members],
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(primary_key=True, default=uuid.uuid4)


def created_at_col() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now())


# --- enums ------------------------------------------------------------------


class TenantPlan(enum.StrEnum):
    FREE = "free"
    PRO = "pro"


class TenantStatus(enum.StrEnum):
    ACTIVE = "active"
    SUSPENDED = "suspended"


class Role(enum.StrEnum):
    TENANT_ADMIN = "tenant_admin"
    RECEPTIONIST = "receptionist"
    STAFF = "staff"


# --- global (not tenant-scoped) tables ---------------------------------------


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = uuid_pk()
    slug: Mapped[str] = mapped_column(unique=True)
    name: Mapped[str]
    plan: Mapped[TenantPlan] = mapped_column(pg_enum(TenantPlan, "tenant_plan"))
    timezone: Mapped[str]
    status: Mapped[TenantStatus] = mapped_column(pg_enum(TenantStatus, "tenant_status"))
    created_at: Mapped[datetime] = created_at_col()


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = uuid_pk()
    email: Mapped[str] = mapped_column(CITEXT, unique=True)
    password_hash: Mapped[str]
    full_name: Mapped[str]
    is_superadmin: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = created_at_col()


class TenantMembership(Base):
    __tablename__ = "tenant_memberships"

    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), primary_key=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    role: Mapped[Role] = mapped_column(pg_enum(Role, "tenant_role"))
    created_at: Mapped[datetime] = created_at_col()


# --- tenant-scoped tables (every one has tenant_id + an RLS policy) ----------


class Customer(Base):
    __tablename__ = "customers"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str]
    phone: Mapped[str]
    email: Mapped[str | None]
    created_at: Mapped[datetime] = created_at_col()


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    actor_type: Mapped[str]
    actor_id: Mapped[str]
    action: Mapped[str]
    entity: Mapped[str]
    entity_id: Mapped[str]
    diff: Mapped[dict[str, Any]] = mapped_column(default=dict)
    request_id: Mapped[str | None] = mapped_column(Text)
    trace_id: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = created_at_col()


class Service(Base):
    __tablename__ = "services"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str]
    duration_min: Mapped[int]
    price_paise: Mapped[int] = mapped_column(BigInteger)
    buffer_min: Mapped[int] = mapped_column(default=0)
    active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = created_at_col()


class Staff(Base):
    __tablename__ = "staff"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    display_name: Mapped[str]
    avatar_key: Mapped[str | None]
    active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = created_at_col()


class StaffService(Base):
    __tablename__ = "staff_services"

    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"), primary_key=True)
    service_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("services.id"), primary_key=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))


class WorkingHours(Base):
    __tablename__ = "working_hours"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"))
    weekday: Mapped[int] = mapped_column(SmallInteger)
    start_time: Mapped[time] = mapped_column(Time)
    end_time: Mapped[time] = mapped_column(Time)


class TimeOff(Base):
    __tablename__ = "time_off"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"))
    period: Mapped[Range[datetime]] = mapped_column(TSTZRANGE)
    reason: Mapped[str | None]
    created_at: Mapped[datetime] = created_at_col()
