"""ORM models. The schema itself is owned by hand-written Alembic migrations (RLS policies and
exclusion constraints can't be autogenerated), so these classes must mirror migrations/versions/*.
"""

import enum
import uuid
from datetime import datetime, time
from typing import Any

from sqlalchemy import BigInteger, DateTime, Enum, ForeignKey, SmallInteger, Text, Time, func
from sqlalchemy.dialects.postgresql import ARRAY, CITEXT, JSONB, TSTZRANGE, UUID, Range
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    type_annotation_map = {dict[str, Any]: JSONB, uuid.UUID: UUID(as_uuid=True)}


def pg_enum(enum_cls: type[enum.Enum], name: str) -> Enum:
    """Map a Python enum to an existing Postgres enum type, storing .value (not the member name)."""
    return Enum(
        enum_cls,
        name=name,
        create_type=False,
        values_callable=lambda members: [m.value for m in members],
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(primary_key=True, default=uuid.uuid4)


def created_at_col() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now())


# --- enums ------------------------------------------------------------------


class TenantPlan(enum.StrEnum):
    FREE = "free"
    PRO = "pro"


class TenantStatus(enum.StrEnum):
    ACTIVE = "active"
    SUSPENDED = "suspended"


class Role(enum.StrEnum):
    TENANT_ADMIN = "tenant_admin"
    RECEPTIONIST = "receptionist"
    STAFF = "staff"


# --- global (not tenant-scoped) tables ---------------------------------------


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = uuid_pk()
    slug: Mapped[str] = mapped_column(unique=True)
    name: Mapped[str]
    plan: Mapped[TenantPlan] = mapped_column(pg_enum(TenantPlan, "tenant_plan"))
    timezone: Mapped[str]
    status: Mapped[TenantStatus] = mapped_column(pg_enum(TenantStatus, "tenant_status"))
    created_at: Mapped[datetime] = created_at_col()


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = uuid_pk()
    email: Mapped[str] = mapped_column(CITEXT, unique=True)
    password_hash: Mapped[str]
    full_name: Mapped[str]
    is_superadmin: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = created_at_col()


class TenantMembership(Base):
    __tablename__ = "tenant_memberships"

    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), primary_key=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    role: Mapped[Role] = mapped_column(pg_enum(Role, "tenant_role"))
    created_at: Mapped[datetime] = created_at_col()


# --- tenant-scoped tables (every one has tenant_id + an RLS policy) ----------


class Customer(Base):
    __tablename__ = "customers"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str]
    phone: Mapped[str]
    email: Mapped[str | None]
    created_at: Mapped[datetime] = created_at_col()


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    actor_type: Mapped[str]
    actor_id: Mapped[str]
    action: Mapped[str]
    entity: Mapped[str]
    entity_id: Mapped[str]
    diff: Mapped[dict[str, Any]] = mapped_column(default=dict)
    request_id: Mapped[str | None] = mapped_column(Text)
    trace_id: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = created_at_col()


class Service(Base):
    __tablename__ = "services"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str]
    duration_min: Mapped[int]
    price_paise: Mapped[int] = mapped_column(BigInteger)
    buffer_min: Mapped[int] = mapped_column(default=0)
    active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = created_at_col()


class Staff(Base):
    __tablename__ = "staff"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    display_name: Mapped[str]
    avatar_key: Mapped[str | None]
    active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = created_at_col()


class StaffService(Base):
    __tablename__ = "staff_services"

    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"), primary_key=True)
    service_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("services.id"), primary_key=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))


class WorkingHours(Base):
    __tablename__ = "working_hours"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"))
    weekday: Mapped[int] = mapped_column(SmallInteger)
    start_time: Mapped[time] = mapped_column(Time)
    end_time: Mapped[time] = mapped_column(Time)


class TimeOff(Base):
    __tablename__ = "time_off"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"))
    period: Mapped[Range[datetime]] = mapped_column(TSTZRANGE)
    reason: Mapped[str | None]
    created_at: Mapped[datetime] = created_at_col()


class BookingStatus(enum.StrEnum):
    PENDING_PAYMENT = "pending_payment"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"
    NO_SHOW = "no_show"
    COMPLETED = "completed"

    @property
    def is_active(self) -> bool:
        """Active bookings hold their slot (mirrors the exclusion constraint's WHERE clause)."""
        return self in (BookingStatus.PENDING_PAYMENT, BookingStatus.CONFIRMED)


class Booking(Base):
    __tablename__ = "bookings"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    staff_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("staff.id"))
    service_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("services.id"))
    customer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("customers.id"))
    period: Mapped[Range[datetime]] = mapped_column(TSTZRANGE)
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    ends_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    status: Mapped[BookingStatus] = mapped_column(pg_enum(BookingStatus, "booking_status"))
    price_paise: Mapped[int] = mapped_column(BigInteger)
    notes: Mapped[str | None]
    version: Mapped[int] = mapped_column(default=1)
    reminder_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = created_at_col()
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class IdempotencyKey(Base):
    __tablename__ = "idempotency_keys"

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), primary_key=True)
    key: Mapped[str] = mapped_column(primary_key=True)
    request_hash: Mapped[str]
    response_status: Mapped[int | None]
    response_body: Mapped[dict[str, Any] | None]
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = created_at_col()


class RefreshToken(Base):
    __tablename__ = "refresh_tokens"

    id: Mapped[uuid.UUID] = uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"))
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tenants.id"))
    family_id: Mapped[uuid.UUID]
    token_hash: Mapped[str] = mapped_column(unique=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    replaced_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("refresh_tokens.id"))
    created_at: Mapped[datetime] = created_at_col()


class ApiKey(Base):
    __tablename__ = "api_keys"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    name: Mapped[str]
    prefix: Mapped[str] = mapped_column(unique=True)
    key_hash: Mapped[str]
    scopes: Mapped[list[str]] = mapped_column(ARRAY(Text))
    rate_limit_per_min: Mapped[int] = mapped_column(default=600)
    created_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = created_at_col()


class OutboxEvent(Base):
    __tablename__ = "outbox_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    aggregate_type: Mapped[str]
    aggregate_id: Mapped[str]
    event_type: Mapped[str]
    payload: Mapped[dict[str, Any]]
    created_at: Mapped[datetime] = created_at_col()
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attempts: Mapped[int] = mapped_column(default=0)
    last_error: Mapped[str | None]


class ConsumerInbox(Base):
    __tablename__ = "consumer_inbox"

    consumer: Mapped[str] = mapped_column(primary_key=True)
    event_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("outbox_events.id"), primary_key=True
    )
    processed_at: Mapped[datetime] = created_at_col()


class WebhookEndpoint(Base):
    __tablename__ = "webhook_endpoints"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    url: Mapped[str]
    secret_enc: Mapped[str]
    events: Mapped[list[str]] = mapped_column(ARRAY(Text))
    active: Mapped[bool] = mapped_column(default=True)
    consecutive_failures: Mapped[int] = mapped_column(default=0)
    disabled_reason: Mapped[str | None]
    created_at: Mapped[datetime] = created_at_col()


class DeliveryStatus(enum.StrEnum):
    PENDING = "pending"
    DELIVERED = "delivered"
    DEAD = "dead"


class WebhookDelivery(Base):
    __tablename__ = "webhook_deliveries"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    endpoint_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("webhook_endpoints.id"))
    outbox_event_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("outbox_events.id"))
    event_type: Mapped[str]
    status: Mapped[DeliveryStatus] = mapped_column(
        pg_enum(DeliveryStatus, "delivery_status"), default=DeliveryStatus.PENDING
    )
    attempt: Mapped[int] = mapped_column(default=0)
    status_code: Mapped[int | None]
    response_ms: Mapped[int | None]
    last_error: Mapped[str | None]
    next_retry_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = created_at_col()


class Payment(Base):
    __tablename__ = "payments"

    id: Mapped[uuid.UUID] = uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"))
    booking_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("bookings.id"))
    provider: Mapped[str]
    provider_ref: Mapped[str]
    amount_paise: Mapped[int] = mapped_column(BigInteger)
    status: Mapped[str]
    raw: Mapped[dict[str, Any]]
    created_at: Mapped[datetime] = created_at_col()
